#!/usr/bin/env python3
"""Emit the Skia console's OS-mark table from the assets/os-icons masters.

    crates/pf-console-ui/src/os_marks.rs    in-session console UI, Skia Path::from_svg

The console parses SVG path data at runtime, so unlike the GTK/Windows/Apple clients it needs
no baked raster or PDF — it needs the path string. And unlike the three hand-kept inline
registries (web, Decky, Android), it is generated outright for the same reason the
launcher-icon tables are: a dozen-odd paths of up to 3.5 kB each, where one mangled character
is a silently wrong logo that no test would catch.

Always emits EVERY master, whatever tokens gen-os-icons.sh was invoked with — this is one file,
and a partial rewrite would drop the rest.

Usage: python3 scripts/gen_os_mark_table.py     (from anywhere; paths are repo-relative)
"""

from __future__ import annotations

import pathlib
import re
import shutil
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MASTERS = ROOT / "assets" / "os-icons"
OUT = "crates/pf-console-ui/src/os_marks.rs"

BANNER = (
    "GENERATED by scripts/gen_os_mark_table.py from the assets/os-icons masters.\n"
    "Do not edit by hand — re-run `bash scripts/gen-os-icons.sh` instead.\n"
    "Per-mark provenance and licensing: assets/os-icons/README.md."
)


def mark(token: str) -> tuple[str, str, float, float]:
    """(token, path data, viewport width, viewport height) for one master."""
    svg = (MASTERS / f"{token}.svg").read_text()
    box = re.search(r'viewBox="([^"]+)"', svg).group(1)
    paths = re.findall(r'<path[^>]*\sd="([^"]+)"', svg)
    if len(paths) != 1:
        sys.exit(f"{token}: expected exactly one <path>, found {len(paths)}")
    d = paths[0]
    if any(c in d for c in '\n\t"\\'):
        sys.exit(f"{token}: path data must be single-line and free of quotes/backslashes")
    _, _, w, h = box.split()
    return token, d, float(w), float(h)


# Sorted so the emitted file has a stable order across runs and machines.
TOKENS = sorted(p.stem for p in MASTERS.glob("*.svg"))
MARKS = [mark(t) for t in TOKENS]

# `!r` on a float always writes a decimal point (`384.0`, never `384`), which matters: the
# table's type is `f32` and a bare integer literal is a type error, not a coercion.
rows = "\n".join(f'    ("{t}", {w!r}, {h!r}, "{d}"),' for t, d, w, h in MARKS)
banner = "\n".join(f"//! {line}".rstrip() for line in BANNER.splitlines())

body = f"""{banner}
//!
//! Host-tile OS marks, fitted into a destination rect.
//!
//! Tokens come from [`pf_client_core::os::os_icon_tokens`] (most-specific-first,
//! brand aliases included). This module only maps those tokens to path art and
//! letterboxes them. `None` means no art — the tile keeps its monogram.

use skia_safe::{{Matrix, Path, Rect}};
use std::collections::HashMap;
use std::sync::{{Mutex, OnceLock}};

type Glyph = (Path, f32, f32);

/// Token → parsed mark. `None` caches a miss so a bad token is not reparsed every frame.
/// Named: `clippy::type_complexity` rejects the inline form, and this file is generated.
type GlyphCache = HashMap<String, Option<Glyph>>;

const GLYPHS: &[(&str, f32, f32, &str)] = &[
{rows}
];

/// Parse once per token. `Path::from_svg` on a 3 kB string is not free, and the
/// home carousel redraws every frame.
fn glyph(token: &str) -> Option<Glyph> {{
    static CACHE: OnceLock<Mutex<GlyphCache>> = OnceLock::new();
    let cache = CACHE.get_or_init(|| Mutex::new(HashMap::new()));
    let mut cache = cache.lock().ok()?;
    if let Some(hit) = cache.get(token) {{
        return hit.clone();
    }}
    let built = GLYPHS
        .iter()
        .find(|(t, ..)| *t == token)
        .and_then(|(_, w, h, d)| Path::from_svg(d).map(|p| (p, *w, *h)));
    cache.insert(token.to_string(), built.clone());
    built
}}

/// Fitted mark for an OS-identity `chain`, aspect preserved — masters are not all square.
/// `None` when no token has art; the tile then draws its monogram. Partial chains still
/// resolve because the shared resolver walks most-specific-first.
pub fn os_mark(chain: &str, dst: Rect) -> Option<Path> {{
    let (path, vw, vh) = pf_client_core::os::os_icon_tokens(chain)
        .into_iter()
        .find_map(|token| glyph(&token))?;
    let scale = (dst.width() / vw).min(dst.height() / vh);
    let mut m = Matrix::new_identity();
    m.set_scale((scale, scale), None);
    m.post_translate((
        dst.left + (dst.width() - vw * scale) / 2.0,
        dst.top + (dst.height() - vh * scale) / 2.0,
    ));
    Some(path.with_transform(&m))
}}

#[cfg(test)]
mod tests {{
    use super::*;

    /// A master that fails to parse is a tile that silently loses its icon.
    #[test]
    fn every_glyph_parses() {{
        for (token, ..) in GLYPHS {{
            assert!(glyph(token).is_some(), "{{token}} failed to parse");
        }}
    }}

    /// Most-specific-first through the shared resolver; `steamos` → Steam is the alias, not table order.
    #[test]
    fn chains_resolve_most_specific_first() {{
        let dst = Rect::from_wh(64.0, 64.0);
        for chain in [
            "windows",
            "linux",
            "linux/arch/steamos",
            "linux/fedora/bazzite",
            "macos",
        ] {{
            assert!(os_mark(chain, dst).is_some(), "{{chain}} resolved nothing");
        }}
        let known = os_mark("linux/debian/raspbian", dst);
        assert!(
            known.is_some(),
            "an unknown leaf must fall back to its family"
        );
    }}

    #[test]
    fn unknown_chain_draws_nothing() {{
        let dst = Rect::from_wh(64.0, 64.0);
        assert!(os_mark("", dst).is_none());
        assert!(os_mark("plan9/glenda", dst).is_none());
        assert!(os_mark("!!!/???", dst).is_none());
    }}

    /// Letterboxed, never stretched. Apple's master is 384×512; Windows is 24×24.
    #[test]
    fn mark_is_contained_and_centred() {{
        let dst = Rect::from_xywh(10.0, 20.0, 80.0, 40.0);
        let b = os_mark("apple", dst).unwrap().compute_tight_bounds();
        assert!(b.width() <= dst.width() + 0.5 && b.height() <= dst.height() + 0.5);
        assert!((b.center_x() - dst.center_x()).abs() < 1.0);
        assert!((b.center_y() - dst.center_y()).abs() < 1.0);
    }}
}}
"""

path = ROOT / OUT
path.write_text(body)

# CI fmt-gates the whole tree, so a generator that emits anything rustfmt would rewrite leaves
# every regeneration one dirty file away from a blocked commit. Formatting the output here is
# what keeps this template from having to stay hand-wrapped to rustfmt's taste.
if shutil.which("rustfmt"):
    subprocess.run(["rustfmt", "--edition", "2024", str(path)], check=True)

print(f"  {OUT} ({path.stat().st_size:,} bytes, {len(MARKS)} marks)")
